name: main
# This workflow is triggered on pushes to the repository.
on: [pull_request]

jobs:
  build:

    name: Check
    # This job runs on Linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x' 
      - run: npm install
      - name: Validate
        run: node index.js